### ISSUE TITLE
How to deal with CORS? It is driving me crazy

### ISSUE THREAD

**Issue by Victorcorcos** [hasura/graphiql-online#7]
I am trying to connect the `https://graphiql-online.com/graphiql` with my local host server, but I am **unable to execute any query due to CORS policy**.

![Screen Shot 2020-04-13 at 17 21 43](https://user-images.githubusercontent.com/7637806/79157627-4e9ccd00-7dab-11ea-9b80-91b1e05dd49c.png)

The console log says...

graphiql:1 Access to fetch at 'http://localhost:3000/graphiql' from origin 'https://graphiql-online.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

How can I handle this?

**Comment by Victorcorcos** [comment]
`rack-cors` gem handled this issue.

**Comment by sumit9133** [comment]
Hi-how did you handle it?
